#docker run \
#-v /absolute/path/to/luxembourg.osm.pbf:/data/region.osm.pbf \
#-v osm-data:/data/database/ \
#overv/openstreetmap-tile-server \
#import

# http://localhost:9000/tile/14/8806/5375.png

#version: '3'
#services:
#  tile-server:
#    image: overv/openstreetmap-tile-server
#    volumes:
#      - ./berlin/berlin-latest.osm.pbf:/data/region.osm.pbf
#      - ./berlin:/data/database
#    ports:
#      - 9000:80
#    command:
#      - run





# Set up volume data for tile server
# docker volume create osm-data
# docker run -v /home/sss/Documents/dev/workspace/order-taxi-app/dev/berlin/berlin-latest.osm.pbf:/data/region.osm.pbf -v osm-data:/data/database/ overv/openstreetmap-tile-server     import


# Start this:
# docker run -t -i -p 5000:5000 -v "${PWD}/berlin:/data" osrm/osrm-backend osrm-routed --algorithm mld /data/berlin-latest.osrm

version: '3'
services:
  zookeeper:
    image: bitnami/zookeeper
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: bitnami/kafka
    ports:
      - "9092:9092"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
    depends_on:
      - zookeeper
  mongo:
    image: mongo
    restart: always
    container_name: mongo-docker
    environment:
#      MONGO_INITDB_ROOT_USERNAME: mongoadmin
#      MONGO_INITDB_ROOT_PASSWORD: mongoadmin
      MONGO_INITDB_DATABASE: test
#      MONGODB_AUTH_DATABASE: admin
    ports:
      - "27017:27017"
    volumes:
      - ./workspace:/workspace
      - type: volume
        source: mongodb_data_volume
        target: /data/db
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - "28081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
#      ME_CONFIG_BASICAUTH_USERNAME: admin
#      ME_CONFIG_BASICAUTH_PASSWORD: admin
      ME_CONFIG_MONGODB_AUTH_DATABASE: admin
#      ME_CONFIG_MONGODB_ADMINUSERNAME: mongoadmin
#      ME_CONFIG_MONGODB_ADMINPASSWORD: mongoadmin
      ME_CONFIG_MONGODB_URL: mongo://mongoadmin:mongoadmin@mongo:27017/
    depends_on:
      - mongo
  map:
    image: overv/openstreetmap-tile-server
    volumes:
      - osm-data:/data/database/
    ports:
      - "9001:80"
    command: "run"
  cache:
    image: redis
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data

#  redis-ui:
#    image: marian/rebrow
#    ports:
#      - "5001:5001"
#    links:
#      - cache
#  redis-commander:
#    container_name: redis-commander
#    hostname: redis-commander
#    image: rediscommander/redis-commander:latest
#    build: .
#    restart: always
#    environment:
#      - REDIS_HOSTS=cache
#    ports:
#      - 8081:8081

  elasticsearch:
    container_name: es-container
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.0
    environment:
      - xpack.security.enabled=false
      - "discovery.type=single-node"
    ports:
      - 9200:9200
  kibana:
    container_name: kb-container
    image: docker.elastic.co/kibana/kibana:7.11.0
    environment:
      - ELASTICSEARCH_HOSTS=http://es-container:9200
    depends_on:
      - elasticsearch
    ports:
      - 5601:5601

volumes:
  osm-data:
    external: true
  kafka_data:
  zookeeper_data:
  mongodb_data_volume:
    driver: local
  redis-data:
    driver: local



# Startup order
# https://docs.docker.com/compose/startup-order/
# https://stackoverflow.com/questions/50387076/docker-compose-conditional-statements-e-g-add-volume-only-if-condition




