#docker run \
#-v /absolute/path/to/luxembourg.osm.pbf:/data/region.osm.pbf \
#-v osm-data:/data/database/ \
#overv/openstreetmap-tile-server \
#import

# http://localhost:9000/tile/14/8806/5375.png

#version: '3'
#services:
#  tile-server:
#    image: overv/openstreetmap-tile-server
#    volumes:
#      - ./berlin/berlin-latest.osm.pbf:/data/region.osm.pbf
#      - ./berlin:/data/database
#    ports:
#      - 9000:80
#    command:
#      - run

# Set up volume data for tile server
# docker volume create osm-data
# docker run -v /home/sss/Documents/dev/workspace/order-taxi-app/dev/berlin/berlin-latest.osm.pbf:/data/region.osm.pbf -v osm-data:/data/database/ overv/openstreetmap-tile-server     import


# Start this:
# docker run -t -i -p 5000:5000 -v "${PWD}/berlin:/data" osrm/osrm-backend osrm-routed --algorithm mld /data/berlin-latest.osrm

version: '3'
services:
  zookeeper:
    image: bitnami/zookeeper
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: bitnami/kafka
    ports:
      - "9092:9092"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092
    depends_on:
      - zookeeper
  map:
    image: overv/openstreetmap-tile-server
    volumes:
      - osm-data:/data/database/
    ports:
      - "9001:80"
    command: "run"
volumes:
  osm-data:
    external: true
  kafka_data:
  zookeeper_data:

# Startup order
# https://docs.docker.com/compose/startup-order/
# https://stackoverflow.com/questions/50387076/docker-compose-conditional-statements-e-g-add-volume-only-if-condition




